import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'integrations/openai/index': 'src/integrations/openai/index.ts',
    'integrations/anthropic/index': 'src/integrations/anthropic/index.ts',
    'integrations/langchain/index': 'src/integrations/langchain/index.ts',
    'scorers/index': 'src/scorers/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  minify: false,
  outDir: 'dist',
  external: [
    // Core OpenTelemetry (peer dependency)
    '@opentelemetry/api',
    '@opentelemetry/sdk-trace-node',
    '@opentelemetry/sdk-trace-base',
    '@opentelemetry/exporter-trace-otlp-proto',
    '@opentelemetry/exporter-trace-otlp-grpc',
    '@opentelemetry/exporter-metrics-otlp-proto',
    '@opentelemetry/exporter-metrics-otlp-grpc',
    '@opentelemetry/exporter-logs-otlp-proto',
    '@opentelemetry/exporter-logs-otlp-grpc',
    '@opentelemetry/resources',
    '@opentelemetry/semantic-conventions',
    '@opentelemetry/sdk-logs',
    '@opentelemetry/sdk-metrics',
    // Optional peer dependencies (external, user provides)
    'openai',
    '@anthropic-ai/sdk',
    '@langchain/core',
    '@langchain/core/callbacks/base',
    '@langchain/core/load/serializable',
    '@langchain/core/outputs',
    // Protobufjs (transitive dep of OTLP exporters, uses eval for dynamic loading)
    'protobufjs',
    'protobufjs/minimal',
    '@protobufjs/inquire',
    '@protobufjs/fetch',
    '@protobufjs/aspromise',
    '@protobufjs/base64',
    '@protobufjs/codegen',
    '@protobufjs/eventemitter',
    '@protobufjs/float',
    '@protobufjs/path',
    '@protobufjs/pool',
    '@protobufjs/utf8',
  ],
  target: 'node22',
  platform: 'node',
});
