import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'integrations/openai/index': 'src/integrations/openai/index.ts',
    'integrations/anthropic/index': 'src/integrations/anthropic/index.ts',
    'integrations/langchain/index': 'src/integrations/langchain/index.ts',
    'integrations/vercel-ai/index': 'src/integrations/vercel-ai/index.ts',
    'integrations/google/index': 'src/integrations/google/index.ts',
    'integrations/mistral/index': 'src/integrations/mistral/index.ts',
    'integrations/azure/index': 'src/integrations/azure/index.ts',
    'integrations/bedrock/index': 'src/integrations/bedrock/index.ts',
    'integrations/cohere/index': 'src/integrations/cohere/index.ts',
    'scorers/index': 'src/scorers/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  minify: false,
  outDir: 'dist',
  external: [
    // Core OpenTelemetry (peer dependency)
    '@opentelemetry/api',
    '@opentelemetry/sdk-trace-node',
    '@opentelemetry/sdk-trace-base',
    '@opentelemetry/exporter-trace-otlp-proto',
    '@opentelemetry/exporter-trace-otlp-grpc',
    '@opentelemetry/exporter-metrics-otlp-proto',
    '@opentelemetry/exporter-metrics-otlp-grpc',
    '@opentelemetry/exporter-logs-otlp-proto',
    '@opentelemetry/exporter-logs-otlp-grpc',
    '@opentelemetry/resources',
    '@opentelemetry/semantic-conventions',
    '@opentelemetry/sdk-logs',
    '@opentelemetry/sdk-metrics',
    // Optional peer dependencies (external, user provides)
    'openai',
    '@anthropic-ai/sdk',
    '@langchain/core',
    '@langchain/core/callbacks/base',
    '@langchain/core/load/serializable',
    '@langchain/core/outputs',
    'ai',
    '@ai-sdk/openai',
    '@ai-sdk/anthropic',
    '@ai-sdk/google',
    '@ai-sdk/mistral',
    '@ai-sdk/cohere',
    '@ai-sdk/amazon-bedrock',
    '@ai-sdk/azure',
    // New provider SDKs
    '@google/genai',
    '@mistralai/mistralai',
    '@aws-sdk/client-bedrock-runtime',
    'cohere-ai',
    // Protobufjs (transitive dep of OTLP exporters, uses eval for dynamic loading)
    'protobufjs',
    'protobufjs/minimal',
    '@protobufjs/inquire',
    '@protobufjs/fetch',
    '@protobufjs/aspromise',
    '@protobufjs/base64',
    '@protobufjs/codegen',
    '@protobufjs/eventemitter',
    '@protobufjs/float',
    '@protobufjs/path',
    '@protobufjs/pool',
    '@protobufjs/utf8',
  ],
  target: 'node20',
  platform: 'node',
});
